// Loads the ID-stamped panel SVG inline and hands out typed references to the
// interactive elements. The asset is generated by tools/build-panel-svg.mjs.

import panelSvg from '../../assets/panel.svg?raw';
import { CONTROLS, PADS } from '../core/controls-meta';

export interface KnobRef {
  g: SVGGElement;
  cx: number;
  cy: number;
}

export interface FaderRef {
  rect: SVGRectElement;
  minY: number; // handle y at value 1 (top)
  maxY: number; // handle y at value 0 (bottom)
}

export class Panel {
  readonly svg: SVGSVGElement;
  readonly knobs = new Map<number, KnobRef>();   // control index 0..5 (S30..S35)
  readonly faders = new Map<number, FaderRef>(); // control index 6..7 (S36..S37)
  readonly pads: SVGGraphicsElement[] = [];      // P0..P11
  readonly recDots: SVGCircleElement[] = [];     // NoteRec layer badges, P3..P7
  readonly sw1: SVGGElement;
  readonly sw2: SVGGElement;
  readonly ledUser: SVGRectElement;

  constructor(container: HTMLElement) {
    container.innerHTML = panelSvg;
    this.svg = container.querySelector('svg')!;

    for (let i = 0; i < CONTROLS.length; i++) {
      const el = this.svg.querySelector<SVGGraphicsElement>(`#${CONTROLS[i].svgId}`);
      if (!el) throw new Error(`panel.svg is missing #${CONTROLS[i].svgId}`);
      if (el instanceof SVGGElement) {
        this.knobs.set(i, {
          g: el,
          cx: parseFloat(el.dataset.cx!),
          cy: parseFloat(el.dataset.cy!),
        });
      } else {
        this.faders.set(i, {
          rect: el as SVGRectElement,
          minY: parseFloat((el as SVGRectElement).dataset.minY!),
          maxY: parseFloat((el as SVGRectElement).dataset.maxY!),
        });
      }
    }

    for (const pad of PADS) {
      const el = this.svg.querySelector<SVGGraphicsElement>(`#${pad.svgId}`);
      if (!el) throw new Error(`panel.svg is missing #${pad.svgId}`);
      this.pads.push(el);
    }

    // NoteRec layer badges: one dot per gesture pad P3–P7 (P2+pad = that
    // layer's mute/clear), anchored near the top of each pad blob so they
    // stay clear of the centered static pad labels. Generated here rather
    // than in the asset build — they're state UI, not faceplate artwork.
    const ns = 'http://www.w3.org/2000/svg';
    const dots = document.createElementNS(ns, 'g');
    dots.setAttribute('id', 'rec-dots');
    for (let i = 0; i < 5; i++) {
      const bb = this.pads[3 + i].getBBox();
      const c = document.createElementNS(ns, 'circle');
      c.setAttribute('cx', (bb.x + bb.width / 2).toFixed(1));
      c.setAttribute('cy', (bb.y + bb.height * 0.2).toFixed(1));
      c.setAttribute('r', '3');
      c.classList.add('rec-dot', 'hidden');
      dots.appendChild(c);
      this.recDots.push(c);
    }
    this.svg.appendChild(dots);

    this.sw1 = this.svg.querySelector<SVGGElement>('#sw1')!;
    this.sw2 = this.svg.querySelector<SVGGElement>('#sw2')!;
    this.ledUser = this.svg.querySelector<SVGRectElement>('#led-user rect')!;
  }

  elementFor(svgId: string): SVGGraphicsElement | null {
    return this.svg.querySelector<SVGGraphicsElement>(`#${svgId}`);
  }
}
