#!/usr/bin/env python3
"""Generate synth/patterns_gen.h from synth/patterns/<genre>/*.h.

Patterns are tagged by subfolder: synth/patterns/techno/, electro/, idm/.
GENRES below fixes the genre indices and must match the SW1 mapping in
sequencer.h and display/oled_ui.cpp's kSw1Seq (0=IDM 1=Techno 2=Electro —
the physical left/center/right panel order, MANUAL.md's SW1 Genre table).
Within a genre, files are sorted by filename, so the numeric prefix fixes
the S35 variant order.

Each pattern file must define
`static constexpr uint8_t kPat_<genre>_<stem>[7][64]` where <stem> is the
filename without extension (e.g. electro/01_electro2.h ->
kPat_electro_01_electro2). Display name = stem minus the numeric prefix.

Invoked by the Makefile before every build; only rewrites the output when the
content changed so unchanged builds stay incremental.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAT_DIR = ROOT / "synth" / "patterns"
OUT = ROOT / "synth" / "patterns_gen.h"
OUT_TS = ROOT / "visualizer" / "src" / "core" / "patterns-gen.ts"

# Genre index order — must match SW1 in TouchPlaited.cpp / sequencer.h
# (0=IDM 1=Techno 2=Electro, the physical left/center/right panel order).
GENRES = ["idm", "techno", "electro"]


def main() -> int:
    stray = sorted(PAT_DIR.glob("*.h"))
    if stray:
        print(f"gen_patterns: pattern files must live in a genre subfolder "
              f"({', '.join(GENRES)}), found in patterns/ root: "
              + ", ".join(f.name for f in stray), file=sys.stderr)
        return 1
    known = {PAT_DIR / g for g in GENRES}
    unknown = [d for d in PAT_DIR.iterdir() if d.is_dir() and d not in known]
    if unknown:
        print(f"gen_patterns: unknown genre folder(s): "
              + ", ".join(d.name for d in unknown)
              + f" (expected one of: {', '.join(GENRES)})", file=sys.stderr)
        return 1

    entries = []            # flat: (include_path, sym, display_name)
    genre_slots = []        # per genre: list of flat indices
    for genre in GENRES:
        files = sorted((PAT_DIR / genre).glob("*.h"))
        if not files:
            print(f"gen_patterns: no pattern files in {PAT_DIR / genre} — "
                  f"every genre needs at least one (SW1 can select it)",
                  file=sys.stderr)
            return 1
        slots = []
        for f in files:
            sym = f"kPat_{genre}_" + re.sub(r"\W", "_", f.stem)
            text = f.read_text(encoding="utf-8")
            decl = (rf"static\s+constexpr\s+uint8_t\s+{re.escape(sym)}"
                    rf"\s*\[\s*7\s*\]\s*\[\s*64\s*\]")
            if not re.search(decl, text):
                print(f"gen_patterns: {genre}/{f.name} must define "
                      f"'static constexpr uint8_t {sym}[7][64]'",
                      file=sys.stderr)
                found = re.search(r"kPat_\w+", text)
                if found:
                    print(f"gen_patterns:   found '{found.group(0)}' — rename the "
                          f"symbol to '{sym}', or the file to match the symbol "
                          f"(the editor's genre/index/name fields set the symbol)",
                          file=sys.stderr)
                return 1
            name = re.sub(r"^\d+_", "", f.stem)
            slots.append(len(entries))
            entries.append((f"{genre}/{f.name}", sym, name))
        genre_slots.append(slots)

    max_slots = max(len(s) for s in genre_slots)
    lines = [
        "// AUTO-GENERATED by tools/gen_patterns.py from synth/patterns/<genre>/*.h",
        "// Do not edit — add/remove pattern files instead and rebuild.",
        "#pragma once",
        "#include <cstdint>",
        "",
    ]
    lines += [f'#include "patterns/{path}"' for path, _, _ in entries]
    lines += [
        "",
        f"static constexpr int kNumGenres   = {len(GENRES)};",
        f"static constexpr int kNumPatterns = {len(entries)};",
        f"static constexpr int kMaxGenrePatterns = {max_slots};",
        "",
        "// [pattern][track][bar * 16 + step]",
        "static constexpr const uint8_t (*kSeqPatterns[kNumPatterns])[64] = {",
    ]
    lines += [f"    {sym}," for _, sym, _ in entries]
    lines += [
        "};",
        "",
        "// Genre index order matches SW1 (0=IDM 1=Techno 2=Electro).",
        "static constexpr uint8_t kGenrePatternCount[kNumGenres] = {"
        + ", ".join(str(len(s)) for s in genre_slots) + "};",
        "",
        "// kGenrePatternIdx[genre][slot] -> index into kSeqPatterns; unused",
        "// slots repeat the last pattern so any slot index is safe to read.",
        "static constexpr uint8_t kGenrePatternIdx[kNumGenres][kMaxGenrePatterns] = {",
    ]
    for slots in genre_slots:
        padded = slots + [slots[-1]] * (max_slots - len(slots))
        lines.append("    {" + ", ".join(str(i) for i in padded) + "},")
    lines += [
        "};",
        "",
        "[[maybe_unused]] static constexpr const char* kGenreNames[kNumGenres] = {"
        + ", ".join(f'"{g}"' for g in GENRES) + "};",
        "",
        "[[maybe_unused]] static constexpr const char* kSeqPatternNames[kNumPatterns] = {",
    ]
    lines += [f'    "{name}",' for _, _, name in entries]
    lines += ["};", ""]

    content = "\n".join(lines)
    if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
        OUT.write_text(content, encoding="utf-8", newline="\n")
        counts = ", ".join(f"{g}:{len(s)}" for g, s in zip(GENRES, genre_slots))
        print(f"gen_patterns: wrote {OUT.name} ({len(entries)} patterns — {counts})")

    ts_lines = [
        "// AUTO-GENERATED by tools/gen_patterns.py from synth/patterns/<genre>/*.h",
        "// Do not edit — keep in lockstep with ../../../synth/patterns_gen.h.",
        "",
        "// Genre index order matches SW1 (0=IDM 1=Techno 2=Electro).",
        f"export const GENRE_NAMES: readonly string[] = [{', '.join(f'{g!r}' for g in GENRES)}];",
        "",
        "export const SEQ_PATTERN_NAMES: readonly string[] = [",
    ]
    ts_lines += [f"  {name!r}," for _, _, name in entries]
    ts_lines += [
        "];",
        "",
        "// GENRE_PATTERN_IDX[genre][slot] -> index into SEQ_PATTERN_NAMES; unused",
        "// slots repeat the last pattern so any slot index is safe to read.",
        "export const GENRE_PATTERN_IDX: readonly (readonly number[])[] = [",
    ]
    for slots in genre_slots:
        padded = slots + [slots[-1]] * (max_slots - len(slots))
        ts_lines.append("  [" + ", ".join(str(i) for i in padded) + "],")
    ts_lines += [
        "];",
        "",
        "export const GENRE_PATTERN_COUNT: readonly number[] = ["
        + ", ".join(str(len(s)) for s in genre_slots) + "];",
        "",
    ]
    ts_content = "\n".join(ts_lines)
    if not OUT_TS.exists() or OUT_TS.read_text(encoding="utf-8") != ts_content:
        OUT_TS.write_text(ts_content, encoding="utf-8", newline="\n")
        print(f"gen_patterns: wrote {OUT_TS.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
