#!/usr/bin/env python3
"""Generate synth/patterns_gen.h from synth/patterns/*.h.

Each pattern file must define `static constexpr uint8_t kPat_<stem>[7][64]`
where <stem> is the filename without extension (e.g. 01_electro.h ->
kPat_01_electro). Files are registered sorted by filename, so the numeric
prefix fixes the selector order. Display name = stem minus the numeric prefix.

Invoked by the Makefile before every build; only rewrites the output when the
content changed so unchanged builds stay incremental.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAT_DIR = ROOT / "synth" / "patterns"
OUT = ROOT / "synth" / "patterns_gen.h"


def main() -> int:
    files = sorted(PAT_DIR.glob("*.h"))
    if not files:
        print(f"gen_patterns: no pattern files in {PAT_DIR}", file=sys.stderr)
        return 1

    entries = []
    for f in files:
        sym = "kPat_" + re.sub(r"\W", "_", f.stem)
        text = f.read_text(encoding="utf-8")
        decl = rf"static\s+constexpr\s+uint8_t\s+{re.escape(sym)}\s*\[\s*7\s*\]\s*\[\s*64\s*\]"
        if not re.search(decl, text):
            print(f"gen_patterns: {f.name} must define "
                  f"'static constexpr uint8_t {sym}[7][64]'", file=sys.stderr)
            return 1
        name = re.sub(r"^\d+_", "", f.stem)
        entries.append((f.name, sym, name))

    lines = [
        "// AUTO-GENERATED by tools/gen_patterns.py from synth/patterns/*.h",
        "// Do not edit — add/remove pattern files instead and rebuild.",
        "#pragma once",
        "#include <cstdint>",
        "",
    ]
    lines += [f'#include "patterns/{fname}"' for fname, _, _ in entries]
    lines += [
        "",
        f"static constexpr int kNumPatterns = {len(entries)};",
        "",
        "// [pattern][track][bar * 16 + step]",
        "static constexpr const uint8_t (*kSeqPatterns[kNumPatterns])[64] = {",
    ]
    lines += [f"    {sym}," for _, sym, _ in entries]
    lines += [
        "};",
        "",
        "[[maybe_unused]] static constexpr const char* kSeqPatternNames[kNumPatterns] = {",
    ]
    lines += [f'    "{name}",' for _, _, name in entries]
    lines += ["};", ""]

    content = "\n".join(lines)
    if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
        OUT.write_text(content, encoding="utf-8", newline="\n")
        print(f"gen_patterns: wrote {OUT.name} ({len(entries)} patterns: "
              + ", ".join(n for _, _, n in entries) + ")")
    return 0


if __name__ == "__main__":
    sys.exit(main())
