// AUTO-GENERATED by tools/gen_patterns.py from synth/patterns/<genre>/*.h
// Do not edit — keep in lockstep with ../../../synth/patterns_gen.h.

// Genre index order matches SW1 (0=IDM 1=Techno 2=Electro).
export const GENRE_NAMES: readonly string[] = ['idm', 'techno', 'electro'];

export const SEQ_PATTERN_NAMES: readonly string[] = [
  'glitch',
  'fullrandom',
  'stomp',
  '90bpmsofchance',
  'randomrandom',
  'reversedchaos',
  'fourfloor',
  'rolling',
  'minmal',
  'tropicalsunset',
  'minimalreversed',
  'minimalspars',
  'classic',
  'brute',
  'offbeat',
  'claptrap',
  'sizzle',
  'burst',
];

// GENRE_PATTERN_IDX[genre][slot] -> index into SEQ_PATTERN_NAMES; unused
// slots repeat the last pattern so any slot index is safe to read.
export const GENRE_PATTERN_IDX: readonly (readonly number[])[] = [
  [0, 1, 2, 3, 4, 5],
  [6, 7, 8, 9, 10, 11],
  [12, 13, 14, 15, 16, 17],
];

export const GENRE_PATTERN_COUNT: readonly number[] = [6, 6, 6];
